development:
  adapter: postgresql
  database: mutants_development
  pool: 5
  host: localhost

test: &test
  adapter: postgresql
  database: mutants_test
  pool: 5
  host: localhost

staging:
  adapter: postgresql
  database: mutants_staging
  pool: 5
  host: localhost

cucumber:
  <<: *test

production:
